language: node_js
sudo: false
node_js:
- "8"
- "9"
install:
- npm install --verbose
- npm install coveralls
- ls node_modules
- ls -l node_modules/dns-packet
script:
- npm run coverage
after_success:
- npm run coveralls
# cache:
#   directories:
#     - node_modules
